apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eagle-public.fullname" . }}-allow-to-rproxy
  labels:
    {{- include "eagle-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      role: rproxy-eagle-epic
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend-public-eagle-epic
      ports:
        - port: 8080
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eagle-public.fullname" . }}-allow-to-analytics
  labels:
    {{- include "eagle-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: penguin-analytics
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend-public-eagle-epic
      ports:
        - port: 3000
          protocol: TCP
