server {
    listen       8080 default_server;
    server_name  localhost;

    # Security headers
    add_header Content-Security-Policy "default-src * about: data: blob: filesystem: 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'none'";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection 1;
    add_header Cache-Control "no-cache, no-store, must-revalidate";

    # Analytics API reverse proxy
    location /api/analytics {
        proxy_pass http://penguin-analytics-api:3000/events;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Angular app
    location / {
        alias /tmp/app/dist/;
        gzip on;
        gzip_min_length 1000;
        gzip_types *;
        try_files $uri$args $uri$args/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
