apiVersion: v2
name: eagle-public
description: EPIC Public Portal - Environmental Assessment Office public-facing application
type: application
version: 1.0.0
appVersion: "21.0.0"
keywords:
  - angular
  - nginx
  - epic
  - eao
maintainers:
  - name: BC Gov EPIC Team
    url: https://github.com/bcgov/eagle-public
