# Test environment values
replicaCount: 2

image:
  tag: "test"

route:
  enabled: true
  serviceName: rproxy
  targetPort: "8080-tcp"
  host: eagle-test.apps.silver.devops.gov.bc.ca
  path: "/"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
