# Development environment values
replicaCount: 1

image:
  tag: "dev"

route:
  enabled: true
  serviceName: eagle-public
  host: eagle-public-6cdc9e-dev.apps.silver.devops.gov.bc.ca

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
