# Development environment values
replicaCount: 1

image:
  tag: "dev"

route:
  enabled: true
  serviceName: rproxy
  targetPort: "8080-tcp"
  host: eagle-dev.apps.silver.devops.gov.bc.ca
  path: "/"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
