# Test environment values
replicaCount: 2

image:
  tag: "test"

route:
  enabled: false
  host: test.projects.eao.gov.bc.ca

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
