// Local development configuration
// In production, this file is generated by nginx-runtime at container startup

// Analytics API - uses proxy.conf.json to route to localhost:3000/events
const LOCAL_ANALYTICS_API = '/api/analytics';

// Apply configuration
window.localStorage.setItem('from_public_server--deployment_env', 'local');
window.localStorage.setItem('from_public_server--banner_colour', 'red');
window.localStorage.setItem('from_public_server--analytics_api_url', LOCAL_ANALYTICS_API);
