// Development placeholder for publicServerEnvironmentSettings.js
// In production, this file is generated by the nginx-runtime container
// See: openshift/templates/nginx-runtime/s2i/bin/run

// For local development, remove remote_api_path and remote_admin_path from localStorage
// so that the defaults in api.ts are used:
// - apiPath defaults to 'https://eagle-dev.apps.silver.devops.gov.bc.ca/api/public'
// - adminUrl defaults to 'http://localhost:4200/admin'

window.localStorage.removeItem('from_public_server--remote_api_path');
window.localStorage.removeItem('from_public_server--remote_admin_path');
window.localStorage.setItem('from_public_server--deployment_env', 'local');
window.localStorage.setItem('from_public_server--banner_colour', 'red');
window.localStorage.setItem('from_public_server--survey_url', 'null');
window.localStorage.setItem('from_public_server--show_survey_banner', 'false');
window.localStorage.setItem('met-api-url', 'null');
