name: Deploy to Test

on:
  workflow_dispatch:

permissions: write-all

env:
  OPENSHIFT_NAMESPACE_TOOLS: 6cdc9e-tools
  OPENSHIFT_NAMESPACE_TEST: 6cdc9e-test
  IMAGE_NAME: eagle-public
  APP_NAME: eagle-public

jobs:
  deploy:
    name: Deploy to Test
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Log into OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE_TOOLS }}

      - name: Tag image for test
        run: |
          echo "Tagging ci-latest as test..."
          oc -n ${{ env.OPENSHIFT_NAMESPACE_TOOLS }} tag \
            ${{ env.IMAGE_NAME }}:ci-latest ${{ env.IMAGE_NAME }}:test

      - name: Deploy to test
        run: |
          oc -n ${{ env.OPENSHIFT_NAMESPACE_TEST }} rollout restart deployment/${{ env.APP_NAME }}
          oc -n ${{ env.OPENSHIFT_NAMESPACE_TEST }} rollout status deployment/${{ env.APP_NAME }} --timeout=5m
          
          echo "Deployment successful!"
          oc get pods -n ${{ env.OPENSHIFT_NAMESPACE_TEST }} -l app.kubernetes.io/name=${{ env.APP_NAME }}
