name: DEV

on:
  pull_request:
    branches:
      - develop

jobs:

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        shell: bash
        run: |
          echo "::set-env name=SUFFIX::pr-${{ GITHUB_REF#refs/heads/ }}"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy image
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.BUILD_TOKEN }}
          SCRIPT: GIT_BRANCH=${GITHUB_HEAD_REF} openshift/scripts/oc_build_deploy.sh ${SUFFIX} apply
